name: Build Flet App
on:
  push:
    branches: [ main ]
  workflow_dispatch: # <--- This adds the "Run workflow" button!

jobs:
  build:
    name: Build on Runner
    # Match the label you see in your runner settings
    runs-on: [self-hosted, iLibraryApp]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install flet
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        shell: bash

      - name: Build App
        run: |
          # This detects if it's running on Mac or Windows automatically
          if [[ "$OSTYPE" == "darwin"* ]]; then
            flet build macos --no-archive
          else
            flet build windows --no-archive
          fi
        shell: bash

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: flet-app-output
          path: build/